import { ArticleCardBlock, ButtonBlock, CountdownTimerBlock, CouponBannerBlock, FloatingButtonBlock, FooterBlock, FormBlock, HeroBlock, ImageBlock, NavigationBlock, PopupModalBlock, PricingTableBlock, ProductCardBlock, TextBlock, TrustBadgeBlock } from "./blocks/BlockViews";
import type { ReactElement } from "react";
import type { BlockAction, PageBlock } from "./schema";

type RegistryItem = {
  labelKey: string;
  descriptionKey: string;
  category: "common" | "basic" | "marketing" | "commerce" | "content" | "conversion" | "navigation" | "footer" | "media" | "trust";
  icon: string;
  defaultProps: Record<string, any>;
  defaultStyle: PageBlock["style"];
  defaultLayout: PageBlock["layout"];
  defaultAction: BlockAction;
  defaultTranslations: PageBlock["translations"];
  Renderer: (props: { block: PageBlock; locale: string }) => ReactElement;
};

const baseAction: BlockAction = { type: "none", target: "", open_mode: "same_tab", tracking_id: "" };
const baseTranslations = (title: string, body = "Build this section visually.", label = "Open"): PageBlock["translations"] => ({
  en: { title, subtitle: "Site Factory OS", body, label },
  "zh-CN": { title, subtitle: "Site Factory OS", body: "通过可视化画布编辑这个区块。", label: "打开" },
  es: { title, subtitle: "Site Factory OS", body: "Edita este bloque visualmente.", label: "Abrir" },
  vi: { title, subtitle: "Site Factory OS", body: "Chỉnh sửa khối này trực quan.", label: "Mở" }
});

export const blockRegistry: Record<string, RegistryItem> = {
  Hero: { labelKey: "builder.blocks.hero", descriptionKey: "builder.block_desc.hero", category: "common", icon: "LayoutTemplate", defaultProps: {}, defaultStyle: { padding: "0", margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "#products" }, defaultTranslations: baseTranslations("Launch a multilingual site in minutes", "A real hero section rendered in the editor and in dist.", "Start"), Renderer: HeroBlock },
  Text: { labelKey: "builder.blocks.text", descriptionKey: "builder.block_desc.text", category: "basic", icon: "Type", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Text section"), Renderer: TextBlock },
  Heading: { labelKey: "builder.blocks.heading", descriptionKey: "builder.block_desc.heading", category: "basic", icon: "Heading", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Section heading"), Renderer: TextBlock },
  Paragraph: { labelKey: "builder.blocks.paragraph", descriptionKey: "builder.block_desc.paragraph", category: "basic", icon: "Pilcrow", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Paragraph", "Detailed supporting copy for this area."), Renderer: TextBlock },
  Image: { labelKey: "builder.blocks.image", descriptionKey: "builder.block_desc.image", category: "basic", icon: "Image", defaultProps: { imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200" }, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Image block"), Renderer: ImageBlock },
  Button: { labelKey: "builder.blocks.button", descriptionKey: "builder.block_desc.button", category: "common", icon: "MousePointerClick", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "https://example.com" }, defaultTranslations: baseTranslations("Button", "", "Open link"), Renderer: ButtonBlock },
  IconBlock: { labelKey: "builder.blocks.icon", descriptionKey: "builder.block_desc.icon", category: "basic", icon: "Sparkles", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Icon highlight"), Renderer: TrustBadgeBlock },
  Divider: { labelKey: "builder.blocks.divider", descriptionKey: "builder.block_desc.divider", category: "basic", icon: "Minus", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Divider"), Renderer: TextBlock },
  Spacer: { labelKey: "builder.blocks.spacer", descriptionKey: "builder.block_desc.spacer", category: "basic", icon: "MoveVertical", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Spacer"), Renderer: TextBlock },
  Container: { labelKey: "builder.blocks.container", descriptionKey: "builder.block_desc.container", category: "basic", icon: "Box", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Container"), Renderer: TextBlock },
  GridLayout: { labelKey: "builder.blocks.grid_layout", descriptionKey: "builder.block_desc.grid_layout", category: "basic", icon: "Grid3X3", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Grid layout"), Renderer: PricingTableBlock },
  TopNav: { labelKey: "builder.blocks.top_nav", descriptionKey: "builder.block_desc.top_nav", category: "navigation", icon: "Navigation", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "#contact" }, defaultTranslations: { en: { title: "Navigation bar", subtitle: "Home · Features · Content · Contact", body: "", label: "Contact" }, "zh-CN": { title: "导航栏", subtitle: "首页 · 卖点 · 内容 · 联系", body: "", label: "联系" }, es: { title: "Navegación", subtitle: "Inicio · Funciones · Contenido · Contacto", body: "", label: "Contacto" }, vi: { title: "Thanh điều hướng", subtitle: "Trang chủ · Tính năng · Nội dung · Liên hệ", body: "", label: "Liên hệ" } }, Renderer: NavigationBlock },
  LogoBlock: { labelKey: "builder.blocks.logo", descriptionKey: "builder.block_desc.logo", category: "navigation", icon: "Badge", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Logo area"), Renderer: TextBlock },
  MenuBar: { labelKey: "builder.blocks.menu_bar", descriptionKey: "builder.block_desc.menu_bar", category: "navigation", icon: "Menu", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Menu bar"), Renderer: TextBlock },
  LanguageSwitcher: { labelKey: "builder.blocks.language_switcher", descriptionKey: "builder.block_desc.language_switcher", category: "navigation", icon: "Languages", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Language switcher"), Renderer: ButtonBlock },
  Breadcrumbs: { labelKey: "builder.blocks.breadcrumbs", descriptionKey: "builder.block_desc.breadcrumbs", category: "navigation", icon: "GitBranch", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Breadcrumbs"), Renderer: TextBlock },
  SideNav: { labelKey: "builder.blocks.side_nav", descriptionKey: "builder.block_desc.side_nav", category: "navigation", icon: "PanelLeft", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Side navigation"), Renderer: TextBlock },
  FloatingButton: { labelKey: "builder.blocks.floating_button", descriptionKey: "builder.block_desc.floating_button", category: "common", icon: "CircleDot", defaultProps: {}, defaultStyle: {}, defaultLayout: { mode: "fixed", x: 24, y: 24, zIndex: 50, anchor: "bottom-right" }, defaultAction: { ...baseAction, type: "popup", target: "popup_offer", tracking_id: "floating_popup" }, defaultTranslations: baseTranslations("Floating button", "", "Need help?"), Renderer: FloatingButtonBlock },
  PopupModal: { labelKey: "builder.blocks.popup_modal", descriptionKey: "builder.block_desc.popup_modal", category: "common", icon: "PanelTopOpen", defaultProps: { popup_id: "popup_offer", trigger: "button", delay_ms: 0 }, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Limited offer", "This popup is rendered from page.json."), Renderer: PopupModalBlock },
  CountdownTimer: { labelKey: "builder.blocks.countdown_timer", descriptionKey: "builder.block_desc.countdown_timer", category: "marketing", icon: "Timer", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Offer ends soon"), Renderer: CountdownTimerBlock },
  FlashSale: { labelKey: "builder.blocks.flash_sale", descriptionKey: "builder.block_desc.flash_sale", category: "marketing", icon: "Flame", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Limited time campaign"), Renderer: CouponBannerBlock },
  CTASection: { labelKey: "builder.blocks.cta_section", descriptionKey: "builder.block_desc.cta_section", category: "marketing", icon: "Megaphone", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "#contact" }, defaultTranslations: baseTranslations("Ready to start?", "A strong conversion section.", "Start now"), Renderer: HeroBlock },
  AnnouncementBar: { labelKey: "builder.blocks.announcement_bar", descriptionKey: "builder.block_desc.announcement_bar", category: "marketing", icon: "Bell", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Free shipping today"), Renderer: CouponBannerBlock },
  CouponBanner: { labelKey: "builder.blocks.coupon_banner", descriptionKey: "builder.block_desc.coupon_banner", category: "commerce", icon: "TicketPercent", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("SAVE 20% TODAY"), Renderer: CouponBannerBlock },
  ProductCard: { labelKey: "builder.blocks.product_card", descriptionKey: "builder.block_desc.product_card", category: "common", icon: "ShoppingBag", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "product" }, defaultTranslations: baseTranslations("Featured product", "Bound to a real product action.", "View product"), Renderer: ProductCardBlock },
  ProductList: { labelKey: "builder.blocks.product_list", descriptionKey: "builder.block_desc.product_list", category: "commerce", icon: "ShoppingCart", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "product" }, defaultTranslations: baseTranslations("Product list"), Renderer: PricingTableBlock },
  ProductDetail: { labelKey: "builder.blocks.product_detail", descriptionKey: "builder.block_desc.product_detail", category: "commerce", icon: "Package", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "product" }, defaultTranslations: baseTranslations("Product detail"), Renderer: ProductCardBlock },
  PricingTable: { labelKey: "builder.blocks.pricing_table", descriptionKey: "builder.block_desc.pricing_table", category: "commerce", icon: "BadgeDollarSign", defaultProps: { plans: ["Trial", "Pro", "Enterprise"] }, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Plans that scale with you"), Renderer: PricingTableBlock },
  BuyButton: { labelKey: "builder.blocks.buy_button", descriptionKey: "builder.block_desc.buy_button", category: "commerce", icon: "ShoppingBasket", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "product" }, defaultTranslations: baseTranslations("Buy button", "", "Buy now"), Renderer: ButtonBlock },
  PaymentButton: { labelKey: "builder.blocks.payment_button", descriptionKey: "builder.block_desc.payment_button", category: "commerce", icon: "CreditCard", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "https://pay.example.com" }, defaultTranslations: baseTranslations("Payment button", "", "Pay now"), Renderer: ButtonBlock },
  ReviewsList: { labelKey: "builder.blocks.reviews_list", descriptionKey: "builder.block_desc.reviews_list", category: "commerce", icon: "Star", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Customer reviews"), Renderer: TrustBadgeBlock },
  RecommendedProducts: { labelKey: "builder.blocks.recommended_products", descriptionKey: "builder.block_desc.recommended_products", category: "commerce", icon: "Sparkles", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Recommended products"), Renderer: PricingTableBlock },
  ArticleCard: { labelKey: "builder.blocks.article_card", descriptionKey: "builder.block_desc.article_card", category: "common", icon: "Newspaper", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "article" }, defaultTranslations: baseTranslations("Featured article", "Bound to a real article action.", "Read article"), Renderer: ArticleCardBlock },
  ArticleList: { labelKey: "builder.blocks.article_list", descriptionKey: "builder.block_desc.article_list", category: "content", icon: "Files", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "article" }, defaultTranslations: baseTranslations("Article list"), Renderer: PricingTableBlock },
  FAQ: { labelKey: "builder.blocks.faq", descriptionKey: "builder.block_desc.faq", category: "content", icon: "CircleHelp", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Frequently asked questions"), Renderer: TextBlock },
  ImageText: { labelKey: "builder.blocks.image_text", descriptionKey: "builder.block_desc.image_text", category: "content", icon: "Rows3", defaultProps: { imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1000" }, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Image and text"), Renderer: ProductCardBlock },
  StepsFlow: { labelKey: "builder.blocks.steps_flow", descriptionKey: "builder.block_desc.steps_flow", category: "content", icon: "ListChecks", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("How it works"), Renderer: PricingTableBlock },
  Timeline: { labelKey: "builder.blocks.timeline", descriptionKey: "builder.block_desc.timeline", category: "content", icon: "GitCommitVertical", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Timeline"), Renderer: TextBlock },
  NoticeBar: { labelKey: "builder.blocks.notice_bar", descriptionKey: "builder.block_desc.notice_bar", category: "content", icon: "Info", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Notice bar"), Renderer: CouponBannerBlock },
  WhatsAppButton: { labelKey: "builder.blocks.whatsapp_button", descriptionKey: "builder.block_desc.whatsapp_button", category: "conversion", icon: "MessageCircle", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "whatsapp", target: "https://wa.me/15550000000", open_mode: "new_tab" }, defaultTranslations: baseTranslations("WhatsApp", "", "Chat on WhatsApp"), Renderer: ButtonBlock },
  TelegramButton: { labelKey: "builder.blocks.telegram_button", descriptionKey: "builder.block_desc.telegram_button", category: "conversion", icon: "Send", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "telegram", target: "https://t.me/support", open_mode: "new_tab" }, defaultTranslations: baseTranslations("Telegram", "", "Chat on Telegram"), Renderer: ButtonBlock },
  WeChatButton: { labelKey: "builder.blocks.wechat_button", descriptionKey: "builder.block_desc.wechat_button", category: "conversion", icon: "MessagesSquare", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url" }, defaultTranslations: baseTranslations("WeChat", "", "Contact on WeChat"), Renderer: ButtonBlock },
  FacebookButton: { labelKey: "builder.blocks.facebook_button", descriptionKey: "builder.block_desc.facebook_button", category: "conversion", icon: "Facebook", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url" }, defaultTranslations: baseTranslations("Facebook", "", "Open Facebook"), Renderer: ButtonBlock },
  InstagramButton: { labelKey: "builder.blocks.instagram_button", descriptionKey: "builder.block_desc.instagram_button", category: "conversion", icon: "Instagram", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url" }, defaultTranslations: baseTranslations("Instagram", "", "Open Instagram"), Renderer: ButtonBlock },
  ContactForm: { labelKey: "builder.blocks.contact_form", descriptionKey: "builder.block_desc.contact_form", category: "conversion", icon: "Mail", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "/api/v1/forms/submit" }, defaultTranslations: baseTranslations("Contact form", "Capture customer messages.", "Submit"), Renderer: FormBlock },
  SubscribeForm: { labelKey: "builder.blocks.subscribe_form", descriptionKey: "builder.block_desc.subscribe_form", category: "conversion", icon: "AtSign", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "external_url", target: "/api/v1/forms/subscribe" }, defaultTranslations: baseTranslations("Subscribe form", "Collect email subscribers.", "Subscribe"), Renderer: FormBlock },
  SupportEntry: { labelKey: "builder.blocks.support_entry", descriptionKey: "builder.block_desc.support_entry", category: "conversion", icon: "Headphones", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: { ...baseAction, type: "telegram", target: "https://t.me/support" }, defaultTranslations: baseTranslations("Customer support", "", "Contact support"), Renderer: ButtonBlock },
  ClaimCoupon: { labelKey: "builder.blocks.claim_coupon", descriptionKey: "builder.block_desc.claim_coupon", category: "conversion", icon: "Gift", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Claim coupon", "Capture coupon intent.", "Claim"), Renderer: CouponBannerBlock },
  InviteFriend: { labelKey: "builder.blocks.invite_friend", descriptionKey: "builder.block_desc.invite_friend", category: "conversion", icon: "UserPlus", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Invite friends"), Renderer: TextBlock },
  TrustBadge: { labelKey: "builder.blocks.trust_badge", descriptionKey: "builder.block_desc.trust_badge", category: "trust", icon: "ShieldCheck", defaultProps: {}, defaultStyle: { margin: "0 0 24px" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Trusted by operators"), Renderer: TrustBadgeBlock },
  StatsCounter: { labelKey: "builder.blocks.stats_counter", descriptionKey: "builder.block_desc.stats_counter", category: "trust", icon: "BarChart3", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("10,000+ launches"), Renderer: TrustBadgeBlock },
  Testimonials: { labelKey: "builder.blocks.testimonials", descriptionKey: "builder.block_desc.testimonials", category: "trust", icon: "Quote", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Customer testimonials"), Renderer: TrustBadgeBlock },
  BrandLogos: { labelKey: "builder.blocks.brand_logos", descriptionKey: "builder.block_desc.brand_logos", category: "trust", icon: "Handshake", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Partner brands"), Renderer: TrustBadgeBlock },
  SecurePayment: { labelKey: "builder.blocks.secure_payment", descriptionKey: "builder.block_desc.secure_payment", category: "trust", icon: "LockKeyhole", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Secure payment"), Renderer: TrustBadgeBlock },
  Guarantee: { labelKey: "builder.blocks.guarantee", descriptionKey: "builder.block_desc.guarantee", category: "trust", icon: "BadgeCheck", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Guarantee"), Renderer: TrustBadgeBlock },
  Footer: { labelKey: "builder.blocks.footer", descriptionKey: "builder.block_desc.footer", category: "footer", icon: "PanelBottom", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: { en: { title: "Footer", subtitle: "Privacy · Terms · Contact", body: "Copyright and contact information.", label: "" }, "zh-CN": { title: "页脚", subtitle: "隐私 · 条款 · 联系", body: "版权和联系方式。", label: "" }, es: { title: "Pie de página", subtitle: "Privacidad · Términos · Contacto", body: "Copyright y datos de contacto.", label: "" }, vi: { title: "Chân trang", subtitle: "Quyền riêng tư · Điều khoản · Liên hệ", body: "Bản quyền và thông tin liên hệ.", label: "" } }, Renderer: FooterBlock },
  Copyright: { labelKey: "builder.blocks.copyright", descriptionKey: "builder.block_desc.copyright", category: "footer", icon: "Copyright", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Copyright"), Renderer: TextBlock },
  ContactInfo: { labelKey: "builder.blocks.contact_info", descriptionKey: "builder.block_desc.contact_info", category: "footer", icon: "Contact", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Contact info"), Renderer: TextBlock },
  SocialLinks: { labelKey: "builder.blocks.social_links", descriptionKey: "builder.block_desc.social_links", category: "footer", icon: "Share2", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Social links"), Renderer: ButtonBlock },
  PolicyLinks: { labelKey: "builder.blocks.policy_links", descriptionKey: "builder.block_desc.policy_links", category: "footer", icon: "FileText", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Policy links"), Renderer: TextBlock },
  VideoBlock: { labelKey: "builder.blocks.video", descriptionKey: "builder.block_desc.video", category: "media", icon: "Video", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Video block"), Renderer: ImageBlock },
  Gallery: { labelKey: "builder.blocks.gallery", descriptionKey: "builder.block_desc.gallery", category: "media", icon: "Images", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Gallery"), Renderer: PricingTableBlock },
  EmbedBlock: { labelKey: "builder.blocks.embed", descriptionKey: "builder.block_desc.embed", category: "media", icon: "Code2", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Embed block"), Renderer: TextBlock },
  MapBlock: { labelKey: "builder.blocks.map", descriptionKey: "builder.block_desc.map", category: "media", icon: "MapPinned", defaultProps: {}, defaultStyle: { margin: "0" }, defaultLayout: { mode: "normal" }, defaultAction: baseAction, defaultTranslations: baseTranslations("Map block"), Renderer: ImageBlock }
};

export const componentTypes = Object.keys(blockRegistry);
